config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  get 'home/index'
  devise_for :users

  resources :tasks
  resources :subtasks
end

app/models/subtask.rb
class Subtask < ActiveRecord::Base
  belongs_to :task
  validates :name, :presence => {message: "Subtask name can't be blank"}
  before_save :default_values 

  private
  def default_values
    self.finished ||= false;
    true
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_many :subtasks, :dependent => :delete_all
  before_save :default_values
  validates :name, :presence => {message: "Task name can't be blank"}

  private
  def default_values
    self.finished ||= false
    true
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tasks, :dependent => :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  self.responder = ActionController::Responder
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @my_todo_list = Task.where(:user_id => current_user.id)
    end
  end
end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController
  def new
    @subtask = Subtasks.new(task_id: params[:task_id])
  end

  def edit
    @subtask = Subtask.find(params[:id])
  end

  def create
    @subtask = Subtask.new(subtask_params)
    respond_to do |format|
      if @subtask.save
        format.html {redirect_to :back}
        format.json {render :json => @subtask, status: :ok}
      else
        format.html {render action: "edit"}
        format.json {render :json => @subtask.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    @subtask = Subtask.find(get_id_from_params)

    respond_to do |format|
      if @subtask.update_attributes(subtask_params)
        format.html {redirect_to :back}
        format.json {render json: @subtask, status: "success"}
      else
        format.html {render action: "edit"}
        format.json {render json: @subtask.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @subtask = Subtask.find(get_id_from_params)
    @subtask.destroy
    
    respond_to do |format|
      format.html {redirect_to :back}
      format.json {render json: @subtask, status: "success"}
    end
  end

  private
  def get_id_from_params
    params[:id].to_i != 0 ? params[:id] : params[:subtask][:id]
  end

  def subtask_params
    params.require(:subtask).permit(
      :name, :description, :task_id, :finished
    )
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.where("(user_id = ? OR public = ?) AND finished = ?", current_user.id, true, false)
  end

  def new
    @task = Task.new(user_id: current_user.id)
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      render action: "index"
    else
      render action: "new"
    end
  end

  def edit
    @task =Task.find(params[:id])
  end

  def update
    @task = Task.find(get_id_from_params)

    respond_to do |format|
      if @task.update_attributes(task_params)
        format.html {render action: "index"}
        format.json {render :json => @task, status: :ok}
      else
        format.html {render action: "edit"}
        format.json {render :json => @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task = Task.find(get_id_from_params)
    @task.destroy

    respond_to do |format|
      format.html {render action: "index"}
      format.json {render :json => @task, status: :ok}
    end
  end

  private
  def get_id_from_params
    params[:id].to_i != 0 ? params[:id] : params[:task][:id]
  end

  def task_params
    params.require(:task).permit(
      :name, :description, :public, :user_id, :finished
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/task_helper.rb
module TaskHelper
  def toggle(simple_task)
    simple_task ? "tab" : "collapse"
  end
end

app/views/home/_subtasks.html.erb
<div id="<%=task_id%>" class="collapse in">
<ul class='nav nav-tabs nav-stacked'>
	<% subtasks.each do |subtask| %>
		<li style="white-space: nowrap;">
			<a class='subnavtab' data-toggle="tab"><%= subtask.name %></a>
		</li>
	<% end %>
</ul>
</div>

app/views/home/_tasks.html.erb
<div class="wraper">
<div class="side-nav-container affix-top">
	<ul class='nav nav-tabs nav-stacked'>
		<% tasks.each do |task| %>
			<li>
				<% unless task.subtasks.blank? %>
					<a data-toggle="collapse" href="#<%=task.id%>"><%= task.name %></a>
					<% unless task.subtasks.blank? %>
						<%= render partial: "subtasks", locals: {subtasks: task.subtasks, task_id: task.id} %>
					<% end %>
				<%else%>
				<a data-toggle="tab" href="#<%=task.id%>"><%= task.name %></a>
				<%end%>
			</li>
		<% end %>
	</ul>
</div>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>
	<div class="container">
		<div class="hero-unit span10 pagination-centered">
			<h1>Hello, <%= current_user.email %> </h1>
			<p>This is your personal To-Do List.</p>
			<p><a href="tasks/new" class="btn btn-primary btn-large">New Task</a></p>
		</div>
	</div>
	<br>
		<% if @my_todo_list.blank? %>
			<p>You have nothing to do.</p>
		<% else %>
			<%= render partial: "tasks",  locals: {tasks: @my_todo_list}%>
		<% end %>
<%else%>
	<div class="hero-unit span12 pagination-centered">
		<h1>Hello! </h1>
		<p>Sing up to create your personal To-Do List, and see who needs help.</p>
		<p><a href="users/sign_up" class="btn btn-primary btn-large">Sing up</a></p>
	</div>
<%end%>
<script>
$(document).ready(function() {
	$('.collapse.in').collapse('hide');
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>ToDoList</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-default">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar collapsed" data-toggle="collapse" data-target=".navbar-responsive-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<a class="brand" href="/">To-Do List</a>
			<div class="nav-collapse navbar-responsive-collapse collapse" style="height: 0px;">
				<ul class="nav">
						<% if user_signed_in? %>
							<li class="active"><a href="/tasks">To-Do</a></li>
							<li class="divider-vertical"></li>
							<li><a><%= current_user.email %></a></li>
							<li class="divider-vertical"></li>
							<li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
							<li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
						<% else %>
							<li class="divider-vertical"></li>
							<li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li>
							<li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
						<% end %>
				</ul>
			</div>
		</div>
	</div>
</div>
<% if notice %>
	<p class="alert alert-success"><%= notice %></p>
  <% end %>
<% if alert %>
	<p class="alert alert-danger"><%= alert %></p>
	<% end %>

<%= yield %>

</body>
</html>

app/views/tasks/_options.html.erb
<div class="span2">
	<button class="btn-mini btn-info" onClick="appendForm(<%=task1.id%>, this)">+ Subtask</button>
</div>
<div class="span2">
	<%=button_to 'Edit', edit_task_path(task1), :method => :get, :class=>"btn-mini btn-info"%>
</div>
<div class="spam2">
	<button class="btn-mini btn-danger" onClick="destroyTask(<%=task1.id%>, this)">Delete</button>
</div>

app/views/tasks/_subtasks.html.erb
<% subtasks.each do |subtask| %>
	<li>
		<div class="row" style="border: solid 1px white;">
			<div class="span4">
				<a class='subnavtab' data-toggle="tab"><%= subtask.name %></a>
			</div>
			<div class="span5">
				<%= check_box_tag("finished", subtask.finished?, subtask.finished?, onclick: "subtaskDone(#{subtask.id}, #{subtask.finished?})")%> Finished
			</div>
		</div>
	</li>
<% end %>

app/views/tasks/_tasks.html.erb
<div class="row" style="border: solid 1px white;">
	<div class="span3">
		<a data-toggle="<%=toggle(task.subtasks.blank?)%>" href="#<%=task.id%>"> <%= task.name %> </a>
	</div>
	<div class="span3">
		Ceated by: <b><%= task.user.email %></b>
	</div>
	<div class="span1">
		<label class="checkbox">
			<%= check_box_tag("finished", task.finished?, task.finished?, onclick: "taskDone(#{task.id}, #{task.finished?})")%> Finished
		</label>
	</div>
	<%if task.user.id == current_user.id%>
		<%= render partial: "options", locals: {task1: task}%>
	<%end%>
</div>
<% unless task.subtasks.blank? %>
	<ul class='nav nav-tabs nav-stacked collapse in' id="<%=task.id%>">
		<%= render partial: "subtasks", locals: {subtasks: task.subtasks, task_id: task.id} %>
	</ul>
<% end %>

app/views/tasks/edit.html.erb
<div class='container'>
	<div class='row'>
		<div class='col-md-6'>
			<%= simple_form_for @task do |f| %>
				<% f.error_notification %>
				<div class="form-inputs">
					<%= f.input :name, required: true, autofocus: true %>
					<%= f.input :description %>
					<%= f.input :public %>
				</div>

				<div class="form-actions">
					<%= f.button :submit, "Save" %>
				</div>
			<%end%>
		</div>
	</div>
</div>

app/views/tasks/index.html.erb
<div class='container'>
	<div class="side-nav-container affix-top">
		<% unless @tasks.blank? %>
			<ul class='nav nav-tabs nav-stacked'>
				<% @tasks.each do |task| %>
					<li>
						<%= render partial: "tasks", locals: {task: task} %>
					</li>
				<% end %>
			</ul>
		<% end %>
	</div>
</div>
<script>
$(document).ready(function() {
	$('.collapse.in').collapse('hide');
});
</script>

app/views/tasks/new.html.erb
<div class='container'>
	<div class='row'>
		<div class='col-md-6'>
			<%= simple_form_for @task do |f| %>
				<% f.error_notification %>
				<div class="form-inputs">
					<%= f.input :user_id,  :as => :hidden, :input_html => { :value => "#{current_user.id}" }%>
					<%= f.input :name, required: true, autofocus: true %>
					<%= f.input :description %>
					<%= f.input :public %>
				</div>

				<div class="form-actions">
					<%= f.button :submit, "Save" %>
				</div>
			<%end%>
		</div>
	</div>
</div>